// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/zharzhanov/mercury/internal/domain (interfaces: ContactDetailsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/zharzhanov/mercury/internal/domain"
)

// MockContactDetailsRepository is a mock of ContactDetailsRepository interface.
type MockContactDetailsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactDetailsRepositoryMockRecorder
}

// MockContactDetailsRepositoryMockRecorder is the mock recorder for MockContactDetailsRepository.
type MockContactDetailsRepositoryMockRecorder struct {
	mock *MockContactDetailsRepository
}

// NewMockContactDetailsRepository creates a new mock instance.
func NewMockContactDetailsRepository(ctrl *gomock.Controller) *MockContactDetailsRepository {
	mock := &MockContactDetailsRepository{ctrl: ctrl}
	mock.recorder = &MockContactDetailsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactDetailsRepository) EXPECT() *MockContactDetailsRepositoryMockRecorder {
	return m.recorder
}

// CreateContactDetails mocks base method.
func (m *MockContactDetailsRepository) CreateContactDetails(arg0 context.Context, arg1 *domain.ContactDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContactDetails", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContactDetails indicates an expected call of CreateContactDetails.
func (mr *MockContactDetailsRepositoryMockRecorder) CreateContactDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContactDetails", reflect.TypeOf((*MockContactDetailsRepository)(nil).CreateContactDetails), arg0, arg1)
}

// CreateResidenceContactDetails mocks base method.
func (m *MockContactDetailsRepository) CreateResidenceContactDetails(arg0 context.Context, arg1 *domain.ResidenceContactDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResidenceContactDetails", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResidenceContactDetails indicates an expected call of CreateResidenceContactDetails.
func (mr *MockContactDetailsRepositoryMockRecorder) CreateResidenceContactDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResidenceContactDetails", reflect.TypeOf((*MockContactDetailsRepository)(nil).CreateResidenceContactDetails), arg0, arg1)
}

// ListContactDetails mocks base method.
func (m *MockContactDetailsRepository) ListContactDetails(arg0 context.Context) ([]*domain.ContactDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContactDetails", arg0)
	ret0, _ := ret[0].([]*domain.ContactDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContactDetails indicates an expected call of ListContactDetails.
func (mr *MockContactDetailsRepositoryMockRecorder) ListContactDetails(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContactDetails", reflect.TypeOf((*MockContactDetailsRepository)(nil).ListContactDetails), arg0)
}

// ListResidenceContactDetails mocks base method.
func (m *MockContactDetailsRepository) ListResidenceContactDetails(arg0 context.Context, arg1 domain.ResidenceContactDetailsSearchCriteria) ([]*domain.ResidenceContactDetails, domain.Total, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResidenceContactDetails", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ResidenceContactDetails)
	ret1, _ := ret[1].(domain.Total)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResidenceContactDetails indicates an expected call of ListResidenceContactDetails.
func (mr *MockContactDetailsRepositoryMockRecorder) ListResidenceContactDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResidenceContactDetails", reflect.TypeOf((*MockContactDetailsRepository)(nil).ListResidenceContactDetails), arg0, arg1)
}

// MarkAsDelivered mocks base method.
func (m *MockContactDetailsRepository) MarkAsDelivered(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsDelivered", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsDelivered indicates an expected call of MarkAsDelivered.
func (mr *MockContactDetailsRepositoryMockRecorder) MarkAsDelivered(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsDelivered", reflect.TypeOf((*MockContactDetailsRepository)(nil).MarkAsDelivered), arg0, arg1)
}
