// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/zharzhanov/mercury/internal/domain (interfaces: FiltersRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/zharzhanov/mercury/internal/domain"
)

// MockFiltersRepository is a mock of FiltersRepository interface.
type MockFiltersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFiltersRepositoryMockRecorder
}

// MockFiltersRepositoryMockRecorder is the mock recorder for MockFiltersRepository.
type MockFiltersRepositoryMockRecorder struct {
	mock *MockFiltersRepository
}

// NewMockFiltersRepository creates a new mock instance.
func NewMockFiltersRepository(ctrl *gomock.Controller) *MockFiltersRepository {
	mock := &MockFiltersRepository{ctrl: ctrl}
	mock.recorder = &MockFiltersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiltersRepository) EXPECT() *MockFiltersRepositoryMockRecorder {
	return m.recorder
}

// CreateCity mocks base method.
func (m *MockFiltersRepository) CreateCity(arg0 context.Context, arg1 *domain.City) (domain.CityID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCity", arg0, arg1)
	ret0, _ := ret[0].(domain.CityID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCity indicates an expected call of CreateCity.
func (mr *MockFiltersRepositoryMockRecorder) CreateCity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCity", reflect.TypeOf((*MockFiltersRepository)(nil).CreateCity), arg0, arg1)
}

// CreateDistrict mocks base method.
func (m *MockFiltersRepository) CreateDistrict(arg0 context.Context, arg1 *domain.District) (domain.DistrictID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDistrict", arg0, arg1)
	ret0, _ := ret[0].(domain.DistrictID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDistrict indicates an expected call of CreateDistrict.
func (mr *MockFiltersRepositoryMockRecorder) CreateDistrict(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDistrict", reflect.TypeOf((*MockFiltersRepository)(nil).CreateDistrict), arg0, arg1)
}

// CreateFilter mocks base method.
func (m *MockFiltersRepository) CreateFilter(arg0 context.Context, arg1 string, arg2 *domain.Filter) (*domain.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFilter", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFilter indicates an expected call of CreateFilter.
func (mr *MockFiltersRepositoryMockRecorder) CreateFilter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFilter", reflect.TypeOf((*MockFiltersRepository)(nil).CreateFilter), arg0, arg1, arg2)
}

// DeleteCity mocks base method.
func (m *MockFiltersRepository) DeleteCity(arg0 context.Context, arg1 domain.CityID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCity", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCity indicates an expected call of DeleteCity.
func (mr *MockFiltersRepositoryMockRecorder) DeleteCity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCity", reflect.TypeOf((*MockFiltersRepository)(nil).DeleteCity), arg0, arg1)
}

// DeleteDistrict mocks base method.
func (m *MockFiltersRepository) DeleteDistrict(arg0 context.Context, arg1 domain.DistrictID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDistrict", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDistrict indicates an expected call of DeleteDistrict.
func (mr *MockFiltersRepositoryMockRecorder) DeleteDistrict(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDistrict", reflect.TypeOf((*MockFiltersRepository)(nil).DeleteDistrict), arg0, arg1)
}

// DeleteFilter mocks base method.
func (m *MockFiltersRepository) DeleteFilter(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFilter", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFilter indicates an expected call of DeleteFilter.
func (mr *MockFiltersRepositoryMockRecorder) DeleteFilter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFilter", reflect.TypeOf((*MockFiltersRepository)(nil).DeleteFilter), arg0, arg1, arg2)
}

// ListBuilders mocks base method.
func (m *MockFiltersRepository) ListBuilders(arg0 context.Context) ([]*domain.FilterBuilder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBuilders", arg0)
	ret0, _ := ret[0].([]*domain.FilterBuilder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBuilders indicates an expected call of ListBuilders.
func (mr *MockFiltersRepositoryMockRecorder) ListBuilders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBuilders", reflect.TypeOf((*MockFiltersRepository)(nil).ListBuilders), arg0)
}

// ListCities mocks base method.
func (m *MockFiltersRepository) ListCities(arg0 context.Context, arg1 domain.CitySearchCriteria) ([]*domain.City, domain.Total, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCities", arg0, arg1)
	ret0, _ := ret[0].([]*domain.City)
	ret1, _ := ret[1].(domain.Total)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCities indicates an expected call of ListCities.
func (mr *MockFiltersRepositoryMockRecorder) ListCities(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCities", reflect.TypeOf((*MockFiltersRepository)(nil).ListCities), arg0, arg1)
}

// ListDistricts mocks base method.
func (m *MockFiltersRepository) ListDistricts(arg0 context.Context, arg1 domain.DistrictSearchCriteria) ([]*domain.District, domain.Total, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDistricts", arg0, arg1)
	ret0, _ := ret[0].([]*domain.District)
	ret1, _ := ret[1].(domain.Total)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDistricts indicates an expected call of ListDistricts.
func (mr *MockFiltersRepositoryMockRecorder) ListDistricts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistricts", reflect.TypeOf((*MockFiltersRepository)(nil).ListDistricts), arg0, arg1)
}

// ListFilterKeys mocks base method.
func (m *MockFiltersRepository) ListFilterKeys(arg0 context.Context) ([]*domain.FilterKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilterKeys", arg0)
	ret0, _ := ret[0].([]*domain.FilterKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilterKeys indicates an expected call of ListFilterKeys.
func (mr *MockFiltersRepositoryMockRecorder) ListFilterKeys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilterKeys", reflect.TypeOf((*MockFiltersRepository)(nil).ListFilterKeys), arg0)
}

// ListFilters mocks base method.
func (m *MockFiltersRepository) ListFilters(arg0 context.Context, arg1 string) ([]*domain.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilters", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilters indicates an expected call of ListFilters.
func (mr *MockFiltersRepositoryMockRecorder) ListFilters(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilters", reflect.TypeOf((*MockFiltersRepository)(nil).ListFilters), arg0, arg1)
}

// UpdateCity mocks base method.
func (m *MockFiltersRepository) UpdateCity(arg0 context.Context, arg1 domain.CityID, arg2 *domain.City) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCity", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCity indicates an expected call of UpdateCity.
func (mr *MockFiltersRepositoryMockRecorder) UpdateCity(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCity", reflect.TypeOf((*MockFiltersRepository)(nil).UpdateCity), arg0, arg1, arg2)
}

// UpdateDistrict mocks base method.
func (m *MockFiltersRepository) UpdateDistrict(arg0 context.Context, arg1 domain.DistrictID, arg2 *domain.District) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDistrict", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDistrict indicates an expected call of UpdateDistrict.
func (mr *MockFiltersRepositoryMockRecorder) UpdateDistrict(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDistrict", reflect.TypeOf((*MockFiltersRepository)(nil).UpdateDistrict), arg0, arg1, arg2)
}
