version: "3.3"
services:
  protoc-all:
    image: namely/protoc-all:latest
    command:
      -d ${PROTO_TARGET_DIRECTORY}
      -o api/generated
      -i third_party/googleapis
      -l go
    volumes:
      - ./:/defs