package error

var (
	// ErrBadRouting is returned when an expected path variable is missing.
	// It always indicates programmer error.
	ErrBadRouting = NewErrInternal("inconsistent mapping between route and handler")
)

// DefaultErrResponse is the default error that is generated by the gateway.
// swagger:model defaultErrorResponse
type DefaultErrResponse struct {
	Code    int               `json:"code"`
	Message string            `json:"message"`
	Details map[string]string `json:"details,omitempty"`
}
